/*
 * jQuery plugin for interacting wirh ProtoAPI
 * 
 * Copyright 2012, Oscar Blasco Maestro
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function($)
{
	/*
	 * Base64 encode / decode
	 * http://www.webtoolkit.info/
	 */
	var Base64 = {

	    // private property
	    _keyStr : "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",

	    // public method for encoding
	    encode : function (input) {
	        var output = "";
	        var chr1, chr2, chr3, enc1, enc2, enc3, enc4;
	        var i = 0;

	        input = Base64._utf8_encode(input);

	        while (i < input.length) {

	                chr1 = input.charCodeAt(i++);
	                chr2 = input.charCodeAt(i++);
	                chr3 = input.charCodeAt(i++);

	                enc1 = chr1 >> 2;
	                enc2 = ((chr1 & 3) << 4) | (chr2 >> 4);
	                enc3 = ((chr2 & 15) << 2) | (chr3 >> 6);
	                enc4 = chr3 & 63;

	                if (isNaN(chr2)) {
	                        enc3 = enc4 = 64;
	                } else if (isNaN(chr3)) {
	                        enc4 = 64;
	                }

	                output = output +
	                this._keyStr.charAt(enc1) + this._keyStr.charAt(enc2) +
	                this._keyStr.charAt(enc3) + this._keyStr.charAt(enc4);

	        }

	        return output;
	    },

	    // private method for UTF-8 encoding
	    _utf8_encode : function (string) {
	        string = string.replace(/\r\n/g,"\n");
	        var utftext = '';

	        for (var n = 0; n < string.length; n++) {

	                var c = string.charCodeAt(n);

	                if (c < 128) {
	                        utftext += String.fromCharCode(c);
	                }
	                else if((c > 127) && (c < 2048)) {
	                        utftext += String.fromCharCode((c >> 6) | 192);
	                        utftext += String.fromCharCode((c & 63) | 128);
	                }
	                else {
	                        utftext += String.fromCharCode((c >> 12) | 224);
	                        utftext += String.fromCharCode(((c >> 6) & 63) | 128);
	                        utftext += String.fromCharCode((c & 63) | 128);
	                }

	        }

	        return utftext;
	    },
	}

	/*
	 * RestClient is a thin warper around $.ajax to make things even easier
	 * 
	 */
	var RestClient = function( config ){
		this.config = config;
	}
	RestClient.prototype = {
		/**
		 * Warper around $.ajax for GET method
		 *
		 * @param filter: A json object with the filter to apply to this search. Please refer to ProtoAPI's 
		 *				  documentation for more information regarding filters.
		 * @param callback: a callback to run once the data is received.
		 */
		get: function( filter, callback ){
			var json_data = JSON.stringify( filter );
			json_data = encodeURIComponent( json_data );
			var query_str = '?pointer=' + this.config.pointer + 
							'&limit=' + this.config.limit + 
							'&filter=' + json_data;
			var uri = this.config.apiuri + this.config.classname + query_str;
			this.__ajax( uri, '', 'GET', callback );
			return this;
		},

		/**
		 * Warper around $.ajax for POST method
		 *
		 * @param data: object to post. The current classname is used, in case a '_cls' field is found, 
		 * 				both must match.
		 * @param callback: Called once a response has been received.
		 */
		post: function( data, callback ){
			var json_data = JSON.stringify( data );
			this.__ajax( this.config.apiuri + this.config.classname, json_data, 'POST', callback );
			return this;
		},

		/**
		 * Warper around $.ajax for PUT method
		 *
		 */
		put: function( data, callback ){
			if(!('_id'  in data )){
				return; // silent error
			}
			json_data = JSON.stringify( data );
			var _id = data._id.toString();

			this.__ajax( this.config.apiuri + this.config.classname + '/' + _id, json_data, 'PUT', callback );
			return this;
		},

		/**
		 * Saves an object. If object is new (doesn't contain an '_id' field), a post is issued
		 * and a new id is generated by ProtoAPI. Otherwise a put is executed.
		 *
		 * @param data: Object to save into ProtoAPI
		 * @param callback: If present, it's called upon succesful save with the updated object
		 */
		save: function( data, callback ){
			if( "_id" in data){ // Update
				
			} else { // Create
				this.post( data, function( _data, _cbk ){
					return function( response ){
						_data._id = response.data; // store _id into object
						if( $.isFunction( _cbk ))
						{
							_cbk( _data );
						}
					}
				}( data, callback ));
			}
		},

		__ajax: function( uri, data, method, callback ){
			
			$.ajax({
			    type: method,
			    url: uri,
			    data: data,
			    processData: false,
				beforeSend: this.__serviceAJAX_beforeSend.bind(this),
			    error: function( XMLHttpRequest, textStatus, errorThrown ) { 
				    if( console && console.log )
				    	console.log('ProtoAPI error: ' + errorThrown); 
				},
			    success: function( response ){
					callback( response );
				},
				
			});
		},

		/**
		 * Internal method to create Basic Auth header
		 */
		__makeBasicAuth: function ( user, password ) {
			var tok = user + ':' + password;
			var hash = Base64.encode(tok);
			return 'Basic ' + hash;
		},
		
		/**
		 * jQuery beforeSend hook to inject auth header
		 */
		__serviceAJAX_beforeSend: function( req ){
			req.setRequestHeader('Authorization', 
                   	this.__makeBasicAuth ( this.config.appid, this.config.appkey ));
		},
	}

	var globals = {}

	$.fn.protoapi = function( config ){

		if( config ){
			globals = $.extend(globals, config);
		}

		var options = $.extend(
		{
			/**
			 * A callback method to be called upon an error 
			 */
			error: undefined,

			/**
			 * ProtoAPI's Application Id
			 * An string with your AppID.
			 */
			appid: undefined,

			/**
			 * ProtoAPI's Application Key
			 * An string with either your public or private key for this AppID
			 */
			appkey: undefined,

			/**
			 * ProtoAPI REST frontend URI
			 */
			apiuri: 'http://localhost/api/1/objects/',

			/**
			 * Sets the max amount of objects to retrieve when a GET is issued
			 */
			limit: 50,

			/**
			 * First object's position to retrieve. Use with limit option for paging
			 */
			pointer: 0,

		}, globals);

		options.classname = this.selector;
		return new RestClient( options );

	}

}(jQuery));